### ISSUE TITLE
请问能更新最新的可执行文件么？

### ISSUE THREAD

**Issue by fengixng** [naihe2010/fdupves#2]
现在能下载的可执行文件是13年更新的，能否更新下最新的可执行文件

**Comment by naihe2010** [comment]
http://weibo.com/1025994511/Dry3QsJcB?from=page_1005051025994511_profile&wvr=6&mod=weibotime&type=comment

**Comment by fengixng** [comment]
谢谢

**Comment by fengixng** [comment]
我也反馈一个bug吧，win10情况下首选项点击没反应
PS：这么好的一个工具没有被大力推广真是可惜了

**Comment by naihe2010** [comment]
哈哈哈，不好意思，根本就没有实现首选项，什么平台都没有。
