### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by DRSDavidSoft** [naihe2010/fdupves#3]
Do you provide windows binaries for the recent commits?

**Comment by naihe2010** [comment]
链接: https://pan.baidu.com/s/1tuS6Xmm4WHXTDdZ5M-lYkg 密码: axhr

**Comment by DRSDavidSoft** [comment]
@naihe2010 I guess not then?

**Comment by naihe2010** [comment]
[fdupves-2.0.0-win32.zip](https://github.com/naihe2010/fdupves/files/2114020/fdupves-2.0.0-win32.zip)
