### ISSUE TITLE
Save Perceptual Hash per file hash

### ISSUE THREAD

**Issue by lenisko** [naihe2010/fdupves#5]
It's just idea, but might speedup whole process.

For example we are using this application on set of YouTube videos. 
*  At first run we have `200 files` in there and 3 of them are duplicates. 
* After some time we have `100` more files so instead doing perceptual hash calculation one more time for all `300` files, application could check `sha1, md5, ...` of file and check in database if there's `file_hash:perceptual_hash` combination. 
  * If it's there: we don't have to run `perceptual_hash` calculation again,
  * If not: calculate `perceptual_hash` and save it in database per `file_hash` and keep going.

This could save a loot of time

**Comment by naihe2010** [comment]
This issue is implemented for a long ago. Please look at the source code.
